import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:app_links/app_links.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'firebase_options.dart'; // Generated by 'flutterfire configure'
import 'services/auth_service.dart';
import 'screens/entry_screen.dart';
import 'screens/feedback_form.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
  runApp(const CobryTempCheckApp());
}

class CobryTempCheckApp extends StatefulWidget {
  const CobryTempCheckApp({super.key});

  @override
  State<CobryTempCheckApp> createState() => _CobryTempCheckAppState();
}

class _CobryTempCheckAppState extends State<CobryTempCheckApp> {
  final AuthService _authService = AuthService();
  final _appLinks = AppLinks();

  @override
  void initState() {
    super.initState();
    _initDeepLinks();
  }

  // This function listens for the email link when the app is opened
  void _initDeepLinks() {
    _appLinks.uriLinkStream.listen((Uri? uri) async {
      if (uri != null) {
        final link = uri.toString();
        
        // 1. Check if it's a valid Firebase Auth link
        if (await _authService.isSignInWithEmailLink(link)) {
          final prefs = await SharedPreferences.getInstance();
          final email = prefs.getString('emailForSignIn');

          if (email != null) {
            // 2. Complete the sign-in
            await _authService.completeSignIn(email, link);
            // 3. Clean up the stored email
            await prefs.remove('emailForSignIn');
          }
        }
      }
    });
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Cobry Temp Check',
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        primaryColor: const Color(0xFF00529B), // Cobry Blue
        useMaterial3: true,
      ),
      // StreamBuilder listens to the user's login state
      home: StreamBuilder(
        stream: _authService.userState,
        builder: (context, snapshot) {
          if (snapshot.connectionState == ConnectionState.waiting) {
            return const Scaffold(body: Center(child: CircularProgressIndicator()));
          }
          // If the user is logged in, show the Feedback Form, otherwise show Entry
          if (snapshot.hasData) {
            return const FeedbackForm();
          }
          return const EntryScreen();
        },
      ),
    );
  }
}